name: Test OIDC Connection

on:
  push:
    branches:
      - main
      - feature/lamp-deploy-v2   # optional for testing

jobs:
  test-aws:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: ap-south-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::947999370414:role/github-deploy-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: List Security Groups (Test Permission)
        run: aws ec2 describe-security-groups
